//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.IC.RecursosTexto {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LoggerDoctor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoggerDoctor() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Base.IC.RecursosTexto.LoggerDoctor", typeof(LoggerDoctor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CapaControlador..
        /// </summary>
        public static string CapaControlador {
            get {
                return ResourceManager.GetString("CapaControlador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capa datos..
        /// </summary>
        public static string CapaDatos {
            get {
                return ResourceManager.GetString("CapaDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capa negocio..
        /// </summary>
        public static string CapaNegocio {
            get {
                return ResourceManager.GetString("CapaNegocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La consulta fallo..
        /// </summary>
        public static string ConsultaFallo {
            get {
                return ResourceManager.GetString("ConsultaFallo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar Doctor..
        /// </summary>
        public static string ConsultarDoctor {
            get {
                return ResourceManager.GetString("ConsultarDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar Lista Doctores..
        /// </summary>
        public static string ConsultarListaDoctores {
            get {
                return ResourceManager.GetString("ConsultarListaDoctores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Doctor consultado  correctamente.
        /// </summary>
        public static string DoctorConsultaCorrecta {
            get {
                return ResourceManager.GetString("DoctorConsultaCorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Doctor Guardado..
        /// </summary>
        public static string DoctorGuardado {
            get {
                return ResourceManager.GetString("DoctorGuardado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Doctor con ID {0} no encontrado.
        /// </summary>
        public static string DoctorNoEncontrado {
            get {
                return ResourceManager.GetString("DoctorNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar Doctor..
        /// </summary>
        public static string GuardarDoctor {
            get {
                return ResourceManager.GetString("GuardarDoctor", resourceCulture);
            }
        }
    }
}
