//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.IC.RecursosTexto {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LoggerPaciente {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoggerPaciente() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Base.IC.RecursosTexto.LoggerPaciente", typeof(LoggerPaciente).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capa Controlador..
        /// </summary>
        public static string CapaControlador {
            get {
                return ResourceManager.GetString("CapaControlador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capa Datos..
        /// </summary>
        public static string CapaDatos {
            get {
                return ResourceManager.GetString("CapaDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capa Negocio..
        /// </summary>
        public static string CapaNegocio {
            get {
                return ResourceManager.GetString("CapaNegocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta Exitosa..
        /// </summary>
        public static string ConsultaExitosa {
            get {
                return ResourceManager.GetString("ConsultaExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta paciente exitosa..
        /// </summary>
        public static string ConsultaPacienteExitosa {
            get {
                return ResourceManager.GetString("ConsultaPacienteExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta lista pacientes..
        /// </summary>
        public static string ConsultarListaPacientes {
            get {
                return ResourceManager.GetString("ConsultarListaPacientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta paciente..
        /// </summary>
        public static string ConsultarPaciente {
            get {
                return ResourceManager.GetString("ConsultarPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar paciente..
        /// </summary>
        public static string EditarPaciente {
            get {
                return ResourceManager.GetString("EditarPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se edito el paciente..
        /// </summary>
        public static string EditarPacienteExitoso {
            get {
                return ResourceManager.GetString("EditarPacienteExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se elimino correctamente..
        /// </summary>
        public static string EliminadoCorrectamente {
            get {
                return ResourceManager.GetString("EliminadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar paciente..
        /// </summary>
        public static string EliminarPaciente {
            get {
                return ResourceManager.GetString("EliminarPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paciente con ID {0} no existe.
        /// </summary>
        public static string EliminarPacienteNoExiste {
            get {
                return ResourceManager.GetString("EliminarPacienteNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error consulta lista paciente..
        /// </summary>
        public static string ErrorConsulta {
            get {
                return ResourceManager.GetString("ErrorConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la consulta..
        /// </summary>
        public static string ErrorPaciente {
            get {
                return ResourceManager.GetString("ErrorPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar Paciente..
        /// </summary>
        public static string GuardarPaciente {
            get {
                return ResourceManager.GetString("GuardarPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se guardo el paciente..
        /// </summary>
        public static string PacienteGuardado {
            get {
                return ResourceManager.GetString("PacienteGuardado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El paciente con ID {0} no esta en base de datos..
        /// </summary>
        public static string PacienteNoEncontrado {
            get {
                return ResourceManager.GetString("PacienteNoEncontrado", resourceCulture);
            }
        }
    }
}
